---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: chatbot
  name: chatbot
stringData:
  S3_ACCESS_KEY: "<scw api access key>"
  S3_SECRET_KEY: "<scw api secret key>"
  S3_ENDPOINT: "https://s3.fr-par.scw.cloud"
  S3_REGION: "fr-par"
  S3_BUCKET: "<bucket-name>"
  DB_CFG: "postgres://vector:<db password>@<db internal ip>:5432/vector"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chatbot
  name: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - image: ghcr.io/n-arno/chatbot-rag:latest
        name: chatbot
        envFrom:
        - secretRef:
            name: chatbot
        ports:
        - containerPort: 8080
          name: app
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chatbot
  name: chatbot
spec:
  ports:
  - name: chatbot
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: chatbot
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: caddy
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - image: caddy:alpine
        name: caddy
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        command:
        - caddy
        args:
        - reverse-proxy
        - -f
        - <your-dns-entry>:443
        - -t
        - chatbot:8080
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/scw-loadbalancer-zone: "fr-par-2"
  labels:
    app: caddy
  name: caddy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  loadBalancerIP: <your-lb-ip>
  selector:
    app: caddy
  type: LoadBalancer
